FROM yokito/ssh-jupyterlab-setup

# 設定參數

LABEL maintainer="deep-learning-package-setup @ yokito"

SHELL ["conda", "run", "-n", "jupyterlab", "/bin/bash", "-o", "pipefail", "-c"]

# 設定環境變數
RUN conda install -y numpy matplotlib pandas h5py pillow scipy -c conda-forge 
RUN conda install -y pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia
RUN conda install -y tensorflow keras opencv -c conda-forge
RUN conda install -y scikit-learn scikit-image -c conda-forge
RUN conda install -y transformers -c huggingface

# RUN conda install --yes --file requirements.txt -c conda-forge -c pytorch -c nvidia -c huggingface

# docker build -t yokito/deep-learning-package-setup . --network=host --no-cache
# docker run -it --rm -p 8888:8888 -p 22:22 --gpus all --name deep-learning-package-setup yokito/deep-learning-package-setup
