#!/bin/bash
# Set permissions on a directory
# After any installation, if a directory needs to be (human) user-writable, run this script on it.
# It will make everything in the directory owned by the group ${userGID} and writable by that group.
# Deployments that want to set a specific user id can preserve permissions
# by adding the `--group-add users` line to `docker run`.

# Uses find to avoid touching files that already have the right permissions,
# which would cause a massive image explosion

# Right permissions are:
# group=${userGID}
# AND permissions include group rwX (directory-execute)
# AND directories have setuid,setgid bits set

set -e

for d in "$@"; do
  find "${d}" \
    ! \( \
      -group "${userGID}" \
      -a -perm -g+rwX \
    \) \
    -exec chgrp "${userGID}" -- {} \+ 2>/dev/null || true \
    -exec chmod g+rwX -- {} \+ 2>/dev/null || true
  # setuid, setgid *on directories only*
  find "${d}" \
    \( \
      -type d \
      -a ! -perm -6000 \
    \) \
    -exec chmod +6000 -- {} \+ 2>/dev/null || true
done	
